databases:
  - name: studybud
    databaseName: studybud
    user: admin

services:
  - type: web
    name: studybud
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn studybud.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: studybud
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
